In [1]:
# pip install numpy
import numpy as np

In [3]:
arreglo_np_lista = np.array( [1,2,3] )
arreglo_np_tupla = np.array( (1,2,3) )
print(type(arreglo_np_lista))
print(type(arreglo_np_tupla))
print(arreglo_np_lista)
print(arreglo_np_tupla)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]


In [7]:
np.ones(10000) # np.array

array([1., 1., 1., ..., 1., 1., 1.])

In [8]:
np.zeros(5) # np.array

array([0., 0., 0., 0., 0.])

In [16]:
np.ones( (2, 2, 2, 2) )

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.ones( [2,3] ).shape

(2, 3)

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(-20, -10) # [-20, -10[

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [24]:
np.arange(30, 66) # [30, 66[

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65])

In [26]:
np.arange(-20, -10, 5) # [-20, -10[

array([-20, -15])

In [27]:
np.arange(-20, -10, 2) # [-20, -10[

array([-20, -18, -16, -14, -12])

In [28]:
np.arange(0, 1, 0.1) # [-20, -10[

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [30]:
np.arange(3, 5, 0.1).shape

(20,)

In [32]:
np.arange(3, 5, 0.1).reshape((5,2,2))

array([[[3. , 3.1],
        [3.2, 3.3]],

       [[3.4, 3.5],
        [3.6, 3.7]],

       [[3.8, 3.9],
        [4. , 4.1]],

       [[4.2, 4.3],
        [4.4, 4.5]],

       [[4.6, 4.7],
        [4.8, 4.9]]])

In [33]:
np.arange(3, 5, 0.1).reshape((5,2,2)).flatten()

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [38]:
np.random.randint(0, 10, 5)

array([7, 7, 5, 5, 3])

In [39]:
np.random.rand(6)

array([0.05452329, 0.6090063 , 0.09322498, 0.15315726, 0.96333088,
       0.54225095])

In [40]:
np.random.randint(0, 10, size = 9).reshape((3,3))

array([[2, 4, 7],
       [9, 2, 0],
       [1, 5, 2]])

In [43]:
a = np.array( [
    [1, 2],
    [3, 4]
] )
b = np.array( [
    [5, 6],
    [7, 8]
] )
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [45]:
# Suma
total = a + b
print(a)
print(b)
total

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 6,  8],
       [10, 12]])

In [46]:
# Resta
total = a - b
print(a)
print(b)
total

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[-4, -4],
       [-4, -4]])

In [47]:
# Multiplicacion
total = a * b
print(a)
print(b)
total

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 5, 12],
       [21, 32]])

In [48]:
# Division
total = a / b
print(a)
print(b)
total

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])