In [1]:
# pip install numpy
import numpy as np

In [3]:
arreglo_np_lista = np.array( [1,2,3] )
arreglo_np_tupla = np.array( (1,2,3) )
print(type(arreglo_np_lista))
print(type(arreglo_np_tupla))
print(arreglo_np_lista)
print(arreglo_np_tupla)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]


In [7]:
np.ones(10000) # np.array

array([1., 1., 1., ..., 1., 1., 1.])

In [8]:
np.zeros(5) # np.array

array([0., 0., 0., 0., 0.])

In [16]:
np.ones( (2, 2, 2, 2) )

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.ones( [2,3] ).shape

(2, 3)

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(-20, -10) # [-20, -10[

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [24]:
np.arange(30, 66) # [30, 66[

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65])

In [26]:
np.arange(-20, -10, 5) # [-20, -10[

array([-20, -15])

In [27]:
np.arange(-20, -10, 2) # [-20, -10[

array([-20, -18, -16, -14, -12])

In [28]:
np.arange(0, 1, 0.1) # [-20, -10[

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [30]:
np.arange(3, 5, 0.1).shape

(20,)

In [32]:
np.arange(3, 5, 0.1).reshape((5,2,2))

array([[[3. , 3.1],
        [3.2, 3.3]],

       [[3.4, 3.5],
        [3.6, 3.7]],

       [[3.8, 3.9],
        [4. , 4.1]],

       [[4.2, 4.3],
        [4.4, 4.5]],

       [[4.6, 4.7],
        [4.8, 4.9]]])

In [33]:
np.arange(3, 5, 0.1).reshape((5,2,2)).flatten()

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [38]:
np.random.randint(0, 10, 5)

array([7, 7, 5, 5, 3])

In [39]:
np.random.rand(6)

array([0.05452329, 0.6090063 , 0.09322498, 0.15315726, 0.96333088,
       0.54225095])

In [40]:
np.random.randint(0, 10, size = 9).reshape((3,3))

array([[2, 4, 7],
       [9, 2, 0],
       [1, 5, 2]])

In [43]:
a = np.array( [
    [1, 2],
    [3, 4]
] )
b = np.array( [
    [5, 6],
    [7, 8]
] )
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [45]:
# Suma
total = a + b
print(a)
print(b)
total

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 6,  8],
       [10, 12]])

In [46]:
# Resta
total = a - b
print(a)
print(b)
total

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[-4, -4],
       [-4, -4]])

In [47]:
# Multiplicacion
total = a * b
print(a)
print(b)
total

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 5, 12],
       [21, 32]])

In [48]:
# Division
total = a / b
print(a)
print(b)
total

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [49]:
total = a ** 9
total

array([[     1,    512],
       [ 19683, 262144]])

In [50]:
total = a % 2
total

array([[1, 0],
       [1, 0]])

In [51]:
total = a + 10
total

array([[11, 12],
       [13, 14]])

In [52]:
total = (a * 2) / 5 * 100
total

array([[ 40.,  80.],
       [120., 160.]])

In [54]:
print(a)
print(b)
a < b

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ True,  True],
       [ True,  True]])

In [55]:
a < 3

array([[ True,  True],
       [False, False]])

In [56]:
a[a < 3]

array([1, 2])

In [57]:
a[a >= 3]

array([3, 4])

In [58]:
a += 2

In [59]:
a

array([[3, 4],
       [5, 6]])

In [60]:
a *= 2

In [61]:
a

array([[ 6,  8],
       [10, 12]])

In [63]:
arreglo = np.arange(1,11)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arreglo.sum()
arreglo.min()
arreglo.max()

10

In [67]:
matriz = np.arange(12).reshape(3,4)

In [69]:
print(matriz)
matriz.sum(axis = 0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [70]:
print(matriz)
matriz.sum(axis = 1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [71]:
print(matriz)
matriz.sum()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


66

In [72]:
notas = np.array([1,2,3,5,3,2,7,8,5,3,2,9,7,6])

In [74]:
notas.mean()

4.5

In [75]:
np.median(notas)

4.0

In [76]:
np.std(notas)

2.471263413143742

In [77]:
np.var(notas)

6.107142857142857

In [78]:
path = "./05_salarios.csv"
salarios = np.genfromtxt(path, delimiter= ',')

In [79]:
salarios

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  0., 10., 12., 13.,
       13.,  2.,  1.,  4.,  5.,  6.,  7.,  8.,  9.])

In [80]:
salarios.mean()

6.136363636363637

In [82]:
once = np.arange(11)**2

In [83]:
once

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
once[::2]

array([  0,   4,  16,  36,  64, 100])

In [85]:
once[::3]

array([ 0,  9, 36, 81])

In [86]:

once[::5]

array([  0,  25, 100])

In [87]:
arreglo_split = np.arange(15)
np.split(arreglo_split, 3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [88]:
np.split(arreglo_split, [2,6,9,13])

[array([0, 1]),
 array([2, 3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14])]

In [104]:
salarios

array([ 0.,  1.,  1.,  2.,  2.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,
        7.,  8.,  8.,  9.,  9., 10., 12., 13., 13.])

In [106]:
print(salarios.sort())
print(salarios)

None
[ 0.  1.  1.  2.  2.  3.  4.  4.  5.  5.  6.  6.  7.  7.  8.  8.  9.  9.
 10. 12. 13. 13.]


In [109]:
salarios[::-1].sort()
print(salarios)

[13. 13. 12. 10.  9.  9.  8.  8.  7.  7.  6.  6.  5.  5.  4.  4.  3.  2.
  2.  1.  1.  0.]
